### ISSUE TITLE
Create a bookmarklet

### ISSUE THREAD

**Issue by jordanmack** [zdivozzo/DeleteSite.js#1]
I recommend you create a bookmarklet so we can more easily destroy the pages we are currently viewing. Below is a starting point, but it doesn't work since Github supplies the wrong MIME type for JS files (and also it's against their TOS). Drop it on a real CDN, change the URL, and it's ready to go.

```
javascript:void(function(){document.getElementsByTagName('head')[0].appendChild(document.createElement('script')).src='https://raw.githubusercontent.com/zdivozzo/DeleteSite.js/master/deleteSite.js?'+Math.random();}());
```

**Comment by zdivozzo** [comment]
@jordanmack I like this idea a lot, hoping to get something set up this weekend.

**Comment by jordanmack** [comment]
I just discovered [RawGit](https://rawgit.com/), which solves the CDN problem. Below is the code for a working bookmarklet.

```
javascript:void(function(){document.getElementsByTagName('head')[0].appendChild(document.createElement('script')).src='https://cdn.rawgit.com/zdivozzo/DeleteSite.js/master/deleteSite.js?'+Math.random();}());
```

**Comment by zdivozzo** [comment]
Awesome, thanks man
